### ISSUE TITLE
Make C-extension Ractor-safe

### ISSUE THREAD

**Issue by mohamedhafez** [ruby/readline-ext#22]
In planning ahead to the near future when TruffleRuby can run C-extensions marked with `rb_ext_ractor_safe(true)` in parallel, and for when Ractors are no longer just experimental, it would be great if the C-extension could be made Ractor-safe, or marked as such if it already is so! Would be happy to send in a PR in the later case.

**Comment by tompng** [comment]
Many rl_ functions are not thread safe.
```ruby
Ractor.new{loop{Readline.basic_word_break_characters=" \t\n\"\\'`@$><=;|&{("+'a'*rand(1..100)}}
Readline.readline ">"
>a.[TAB]
[BUG] Segmentation fault at 0x0000000000000000
```

`Readline.pre_input_hook` and `Readline.completion_proc` are not ractor safe. It should not execute/share ractor-unshareable procs in/to another ractor.

Readline-ext is removed from bundled gem because we have Reline now. I think the priority of making Reline work with ractors is higher.

**Comment by mohamedhafez** [comment]
awesome, we're discussing in the TruffleRuby slack, i'll reopen this issue on reline if necessary, thanks for the feedback!
